version: '2'
services:
  db:
    image: postgres
  storage:
    image: ianbytchek/riak-cs
    ports:
      - "8080:8080"
    environment:
      RIAK_CS_BUCKETS: crmv2
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
      - storage